import { combineReducers } from 'redux';
// import {
//   userlogin,
//   kycverify,
//   kycpending,
//   kycreject,
//   kycupdate,
//   stadiumownercreate,
//   stadiumownercount,
//   stadiumownerlist,
//   stadiumeventlist,
//   eventorgcount,
//   kyclistall,
//   privacypolicyadd,
//   privacypolicylist,
//   termsadd,
//   termslist,
//   notifyadd,
//   updateversion,
//   getversion,
//   cataddbanner,
//   catlistbanner,
//   catdeletebanner,
//   mainaddbanner,
//   mainlistbanner,
//   maindeletebanner,
//   playerCount,
//   playerList,
//   stadiumlist,
//   stadiumupdate,
//   issuesList,
//   updateissues,
//   sponseradd,
//   sponserlist,
//   sponserdelete,
//   promocodeadd,
//   marathonlist,
//   formquestion
// } from './reducer';

import * as reducer from './reducer';

export default combineReducers(reducer);

// export default combineReducers({
//   userlogin,
//   kycverify,
//   kycpending,
//   kycreject,
//   kycupdate,
//   stadiumownercreate,
//   stadiumownercount,
//   stadiumownerlist,
//   stadiumeventlist,
//   eventorgcount,
//   kyclistall,
//   privacypolicyadd,
//   privacypolicylist,
//   termsadd,
//   termslist,
//   notifyadd,
//   updateversion,
//   getversion,
//   cataddbanner,
//   catlistbanner,
//   catdeletebanner,
//   mainaddbanner,
//   mainlistbanner,
//   maindeletebanner,
//   playerCount,
//   playerList,
//   issuesList,
//   updateissues,
//   stadiumlist,
//   stadiumupdate,
//   sponserlist,
//   sponseradd,
//   sponserdelete,
//   promocodeadd,
//   marathonlist,
//   formquestion
// });
